# Generated by Django 2.2.16 on 2022-11-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Биография'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(
                choices=[('user', 'User'), ('moderator', 'Moderator'),
                         ('admin', 'Admin')], default='user', max_length=2),
        ),
    ]
