# Generated by Django 3.2.16 on 2022-11-07 00:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0007_auto_20221105_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150,
                                   verbose_name='first name'),
        ),
    ]
